#show "yy": text(fill: green.darken(30%))[*Y*]
#show "nn": text(fill: red.darken(30%))[*N*]

#table(
  columns: 3,
  inset: 7pt,
  [*Instruction*], [*Implemented*], [*Priliminary Tested*],
  [ADD.W], [yy], [yy],
  [SUB.W], [yy], [yy],
  [ADDI.W], [yy], [yy],
  [LU12I.W], [yy], [yy],
  [SLT], [yy], [yy],
  [SLTU], [yy], [yy],
  [SLTI], [yy], [nn],
  [SLTUI], [yy], [nn],
  [PCADDU12I], [yy], [nn],
  [AND], [yy], [nn],
  [OR], [yy], [nn],
  [NOR], [yy], [nn],
  [XOR], [yy], [nn],
  [ANDI], [yy], [nn],
  [ORI], [yy], [nn],
  [XORI], [yy], [nn],
  [MUL.W], [nn], [nn],
  [MULH.W], [nn], [nn],
  [MULH.WU], [nn], [nn],
  [DIV.W], [nn], [nn],
  [DIV.WU], [nn], [nn],
  [MOD.W], [nn], [nn],
  [MOD.WU], [nn], [nn],
  [SLL.W], [yy], [nn],
  [SRL.W], [yy], [nn],
  [SRA.W], [yy], [nn],
  [SLLI.W], [yy], [nn],
  [SRLI.W], [yy], [nn],
  [SRAI.W], [yy], [nn],
  [BEQ], [yy], [nn],
  [BNE], [yy], [nn],
  [BLT], [yy], [nn],
  [BLTU], [yy], [nn],
  [BGE], [yy], [nn],
  [BGEU], [yy], [nn],
  [B], [yy], [nn],
  [BL], [yy], [nn],
  [JIRL], [yy], [nn],
  [LD.B], [yy], [nn],
  [LD.BU], [yy], [nn],
  [LD.H], [yy], [nn],
  [LD.HU], [yy], [nn],
  [LD.W], [yy], [nn],
  [ST.B], [yy], [nn],
  [ST.H], [yy], [nn],
  [ST.W], [yy], [nn],
  [PRELD], [nn], [nn],
  [LL.W], [nn], [nn],
  [SC.W], [nn], [nn],
  [DBAR], [nn], [nn],
  [IBAR], [nn], [nn],
  [SYSCALL], [nn], [nn],
  [BREAK], [nn], [nn],
  [RDCNTVL.W], [nn], [nn],
  [RDCNTVH.W], [nn], [nn],
  [RDCNTID], [nn], [nn],
)
